name: Release

on:
  push:
    branches:
      - feature/ci-release-pipeline
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2

permissions:
  contents: write